<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Recent Reports</h5>
        <div class="btn-group">
            <button class="btn btn-outline-secondary btn-sm">
                <i class="bi bi-download"></i> Download All
            </button>
            <button class="btn btn-outline-secondary btn-sm">
                <i class="bi bi-share"></i> Share
            </button>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Report Name</th>
                        <th>Type</th>
                        <th>Generated Date</th>
                        <th>Generated By</th>
                        <th>Format</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Monthly Academic Performance</td>
                        <td>Academic</td>
                        <td>2024-02-28</td>
                        <td>Admin User</td>
                        <td>PDF</td>
                        <td>
                            <button class="btn btn-sm btn-info me-2" title="View">
                                <i class="bi bi-eye"></i>
                            </button>
                            <button class="btn btn-sm btn-success me-2" title="Download">
                                <i class="bi bi-download"></i>
                            </button>
                            <button class="btn btn-sm btn-danger" title="Delete">
                                <i class="bi bi-trash"></i>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>Q1 Financial Summary</td>
                        <td>Financial</td>
                        <td>2024-02-25</td>
                        <td>Finance Manager</td>
                        <td>Excel</td>
                        <td>
                            <button class="btn btn-sm btn-info me-2" title="View">
                                <i class="bi bi-eye"></i>
                            </button>
                            <button class="btn btn-sm btn-success me-2" title="Download">
                                <i class="bi bi-download"></i>
                            </button>
                            <button class="btn btn-sm btn-danger" title="Delete">
                                <i class="bi bi-trash"></i>
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>Staff Attendance Report</td>
                        <td>Administrative</td>
                        <td>2024-02-20</td>
                        <td>HR Manager</td>
                        <td>PDF</td>
                        <td>
                            <button class="btn btn-sm btn-info me-2" title="View">
                                <i class="bi bi-eye"></i>
                            </button>
                            <button class="btn btn-sm btn-success me-2" title="Download">
                                <i class="bi bi-download"></i>
                            </button>
                            <button class="btn btn-sm btn-danger" title="Delete">
                                <i class="bi bi-trash"></i>
                            </button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- Pagination -->
        <nav class="mt-4">
            <ul class="pagination justify-content-end">
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
                <li class="page-item active"><a class="page-link" href="#">1</a></li>
                <li class="page-item"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="#">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</div>